/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExperienceCreative2RouteImport } from './routes/experience-creative2'
import { Route as ExperienceCreative1RouteImport } from './routes/experience-creative1'
import { Route as IndexRouteImport } from './routes/index'

const ExperienceCreative2Route = ExperienceCreative2RouteImport.update({
  id: '/experience-creative2',
  path: '/experience-creative2',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceCreative1Route = ExperienceCreative1RouteImport.update({
  id: '/experience-creative1',
  path: '/experience-creative1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experience-creative1': typeof ExperienceCreative1Route
  '/experience-creative2': typeof ExperienceCreative2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experience-creative1': typeof ExperienceCreative1Route
  '/experience-creative2': typeof ExperienceCreative2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experience-creative1': typeof ExperienceCreative1Route
  '/experience-creative2': typeof ExperienceCreative2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experience-creative1' | '/experience-creative2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experience-creative1' | '/experience-creative2'
  id: '__root__' | '/' | '/experience-creative1' | '/experience-creative2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienceCreative1Route: typeof ExperienceCreative1Route
  ExperienceCreative2Route: typeof ExperienceCreative2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/experience-creative2': {
      id: '/experience-creative2'
      path: '/experience-creative2'
      fullPath: '/experience-creative2'
      preLoaderRoute: typeof ExperienceCreative2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience-creative1': {
      id: '/experience-creative1'
      path: '/experience-creative1'
      fullPath: '/experience-creative1'
      preLoaderRoute: typeof ExperienceCreative1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienceCreative1Route: ExperienceCreative1Route,
  ExperienceCreative2Route: ExperienceCreative2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
